language: python

os:
  - linux

python:
  - 3.6

addons:
  apt:
    packages:
    - python-setuptools

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda create -n myenv python=3.7
  - conda activate myenv
  - pip install tensorflow==2.3
  - pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install torch_scatter==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.5.0.html
  - pip install torch_cluster==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.5.0.html
  - pip install torch_sparse==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.5.0.html
  - pip install torch-spline-conv==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.5.0.html
  - pip install torch_geometric
  - pip install uproot
  - pip install matplotlib networkx numba scipy numpy comet_ml setGPU pandas mplhep tqdm sklearn


script:
  - mkdir -p data/TTbar_14TeV_TuneCUETP8M1_cfi
  - cd data/TTbar_14TeV_TuneCUETP8M1_cfi
  - wget https://login-1.hep.caltech.edu/~jpata/particleflow/2020-07/TTbar_14TeV_TuneCUETP8M1_cfi/pfntuple_1.root
  - cd ../..
  - mkdir -p data/TTbar_14TeV_TuneCUETP8M1_cfi/raw
  - python test/postprocessing2.py --input data/TTbar_14TeV_TuneCUETP8M1_cfi/pfntuple_1.root --events-per-file 1 --outpath data/TTbar_14TeV_TuneCUETP8M1_cfi/raw --save-normalized-table
  - COMET_API_KEY="bla" python test/train_end2end.py --dataset data/TTbar_14TeV_TuneCUETP8M1_cfi --space_dim 2 --n_train 3 --n_val 2 --model PFNet7 --convlayer gravnet-radius --lr 0.0001 --hidden_dim 32 --n_epochs 2 --l1 1.0 --l2 0.001 --l3 0.0 --target cand --batch_size 1 --dropout 0.2 --disable-comet


