backend: pytorch

batching:
  gpu_size_multiplier: 20

model:
  gnn-lsh:
    conv_type: gnn-lsh
    embedding_dim: 128
    width: 128
    num_convs: 2
    dropout: True

  gravnet:
    conv_type: gravnet
    embedding_dim: 36
    width: 128
    num_convs: 2
    k: 16
    propagate_dimensions: 22
    space_dimensions: 4
    dropout: True

  attention:
    conv_type: attention
    embedding_dim: 128
    width: 128
    num_convs: 2
    k: 16
    propagate_dimensions: 22
    space_dimensions: 4
    dropout: True

train_dataset:
  cms:
    cms_pf_ttbar:
      version: 1.6.0
      batch_size: 5
    cms_pf_qcd:
      version: 1.6.0
      batch_size: 5
    cms_pf_ztt:
      version: 1.6.0
      batch_size: 5
    cms_pf_qcd_high_pt:
      version: 1.6.0
      batch_size: 5
    cms_pf_sms_t1tttt:
      version: 1.6.0
      batch_size: 5
    cms_pf_single_electron:
      version: 1.6.0
      batch_size: 50
    cms_pf_single_gamma:
      version: 1.6.0
      batch_size: 50
    cms_pf_single_pi0:
      version: 1.6.0
      batch_size: 50
    cms_pf_single_neutron:
      version: 1.6.0
      batch_size: 50
    cms_pf_single_pi:
      version: 1.6.0
      batch_size: 50
    cms_pf_single_tau:
      version: 1.6.0
      batch_size: 50
    cms_pf_single_mu:
      version: 1.6.0
      batch_size: 50
    cms_pf_single_proton:
      version: 1.6.0
      batch_size: 50
    cms_pf_multi_particle_gun:
      version: 1.6.0
      batch_size: 50
  clic:
    clic_edm_qq_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_ttbar_pf:
      version: 1.5.0
      batch_size: 100
    # clic_edm_ttbar_pu10_pf:
    #   version: 1.5.0
    #   batch_size: 100
    # clic_edm_ww_fullhad_pf:
    #   version: 1.5.0
    #   batch_size: 100
    # clic_edm_zh_tautau_pf:
    #   version: 1.5.0
    #   batch_size: 100
  delphes:
    delphes_ttbar_pf:
      version: 1.2.0
      batch_size: 10
    delphes_qcd_pf:
      version: 1.2.0
      batch_size: 10

test_dataset:
  cms:
    cms_pf_ttbar:
      version: 1.6.0
      batch_size: 5
    cms_pf_qcd:
      version: 1.6.0
      batch_size: 5
    cms_pf_ztt:
      version: 1.6.0
      batch_size: 5
    cms_pf_qcd_high_pt:
      version: 1.6.0
      batch_size: 5
    cms_pf_sms_t1tttt:
      version: 1.6.0
      batch_size: 5
    cms_pf_single_electron:
      version: 1.6.0
      batch_size: 50
    cms_pf_single_gamma:
      version: 1.6.0
      batch_size: 50
    cms_pf_single_pi0:
      version: 1.6.0
      batch_size: 50
    cms_pf_single_neutron:
      version: 1.6.0
      batch_size: 50
    cms_pf_single_pi:
      version: 1.6.0
      batch_size: 50
    cms_pf_single_tau:
      version: 1.6.0
      batch_size: 50
    cms_pf_single_mu:
      version: 1.6.0
      batch_size: 50
    cms_pf_single_proton:
      version: 1.6.0
      batch_size: 50
    cms_pf_multi_particle_gun:
      version: 1.6.0
      batch_size: 50
  clic:
    clic_edm_qq_pf:
      version: 1.5.0
      batch_size: 100
    clic_edm_ttbar_pf:
      version: 1.5.0
      batch_size: 100
    # clic_edm_ttbar_pu10_pf:
    #   version: 1.5.0
    #   batch_size: 100
    # clic_edm_ww_fullhad_pf:
    #   version: 1.5.0
    #   batch_size: 100
    # clic_edm_zh_tautau_pf:
    #   version: 1.5.0
    #   batch_size: 100
  delphes:
    delphes_ttbar_pf:
      version: 1.2.0
      batch_size: 10
    delphes_qcd_pf:
      version: 1.2.0
      batch_size: 10
